dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- cp decide/local_settings.travis.py decide/local_settings.py
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- psql -U postgres -c "create database decide owner decide"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd decide
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: decide-palkia-django-integ
  strategy: git
  on:
    branch: master
  api_key:
    secure: ZogY+kuIQocp4bQiv+h3ydwP2T+cckvZyf4rkdjqPYYiCRCn0U9Aa1VTAzWh2W/TjfQYHWYLM2snK4NQqVhPJhWTo5X9lC1J+FwUixy70Yziv2Irr3vo5fVoUDN6frCKKN0pEQcp/rKOT6sCaeVVNBTciULERZ+aIeD0vmuZQwatyJfRiSS//eE4W+oDjFZhqeHm1PpOxphefJxxJ0IzeFxGwvUxR/2hSgsOC4qx2IsKfV2Zu4R6fPJ6FS7bQCqDI+b1ZFFokGfWx5hwKRMPR9ntNyVPwV99cmXYpgZFBnON2HRmz5lACBf59TgtoZSLuyqDassSd8rSh6JZ86T8fx08QM1X3kAKSgsoHrGG8mQWX3mVfJtsFNNsI4vuR4sFZNCfEEFmxv8WHIC89/5B8LhB9DviV+lWeroVesNl6/ZzRq1kCNsHuoiIdyqcFFSJF9tyJ1iEOxqNDIyQbrTl5jZoXVMZCHg41mDWV4axv0J83n7m8geR3of7aybT7ecjccM185jo+7HiiIA5r8+GJV1WFBdCqvzj8CZ9qqyX2KKi9seQtU+5V/xxKjBOZFFJDfso23Et7+wz5ynyq2KVmnFX+xwd992WK1e1V21XUX7zkZsn262Br2VGWQYAeR4WDtc8WS28GbBnspIySzeNt0LcKGLApDsAi3YuFkPRRAo=

